[build]
  command = "yarn install --frozen-lockfile --prod && yarn run netlify-zip-it-ship-it-issue-38-workaround"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/.netlify/functions/graphql"
  status = 200
