name: Test

on: [push]

jobs:
    jest:
        name: Jest
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Restore Yarn cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              run: |
                  yarn install --immutable
            - name: Run Jest
              run: |
                  yarn start && yarn test
    eslint:
        name: ESLint
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Restore Yarn cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              run: |
                  yarn install --frozen-lockfile
            - name: Run ESLint
              run: |
                  yarn start && yarn lint:js
    prettier:
        name: Prettier
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@master
            - name: Use Node.js 16.x
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - name: Restore Yarn cache
              uses: actions/cache@v2
              with:
                  path: |
                      node_modules
                      */*/node_modules
                  key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
            - name: Install dependencies
              run: |
                  yarn install --immutable
            - name: Run Prettier
              run: |
                  yarn start && yarn lint:prettier
